# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sdf.xdc

# IP: ip/RAM/RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: ip/prgrom/prgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# Block Designs: bd/CPU/CPU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU || ORIG_REF_NAME==CPU} -quiet] -quiet

# IP: bd/CPU/ip/CPU_StorageTop_0_0/CPU_StorageTop_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_StorageTop_0_0 || ORIG_REF_NAME==CPU_StorageTop_0_0} -quiet] -quiet

# IP: ip/RAM/RAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: bd/CPU/ip/CPU_control32_0_0/CPU_control32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_control32_0_0 || ORIG_REF_NAME==CPU_control32_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_Idecode32_0_0/CPU_Idecode32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Idecode32_0_0 || ORIG_REF_NAME==CPU_Idecode32_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_Ifetc32_0_0/CPU_Ifetc32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Ifetc32_0_0 || ORIG_REF_NAME==CPU_Ifetc32_0_0} -quiet] -quiet

# IP: ip/prgrom/prgrom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# IP: bd/CPU/ip/CPU_Executs32_0_0/CPU_Executs32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_Executs32_0_0 || ORIG_REF_NAME==CPU_Executs32_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_clk_wiz_0_0 || ORIG_REF_NAME==CPU_clk_wiz_0_0} -quiet] -quiet

# XDC: ip/RAM/RAM_ooc.xdc

# XDC: ip/prgrom/prgrom_ooc.xdc

# XDC: ip/RAM/RAM_ooc.xdc

# XDC: ip/prgrom/prgrom_ooc.xdc

# XDC: bd/CPU/CPU_ooc.xdc
