# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/multiplexer.xdc

# Block Designs: bd/mux2x1/mux2x1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1 || ORIG_REF_NAME==mux2x1} -quiet] -quiet

# IP: bd/mux2x1/ip/mux2x1_notgate_0_0/mux2x1_notgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_notgate_0_0 || ORIG_REF_NAME==mux2x1_notgate_0_0} -quiet] -quiet

# IP: bd/mux2x1/ip/mux2x1_orgate_0_0/mux2x1_orgate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_orgate_0_0 || ORIG_REF_NAME==mux2x1_orgate_0_0} -quiet] -quiet

# IP: bd/mux2x1/ip/mux2x1_andgate_0_2/mux2x1_andgate_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_andgate_0_2 || ORIG_REF_NAME==mux2x1_andgate_0_2} -quiet] -quiet

# IP: bd/mux2x1/ip/mux2x1_andgate_0_3/mux2x1_andgate_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux2x1_andgate_0_3 || ORIG_REF_NAME==mux2x1_andgate_0_3} -quiet] -quiet

# XDC: bd/mux2x1/mux2x1_ooc.xdc
