webtalk_init -webtalk_dir F:/Github/Computer_Organization/src/project_14/project_14.sim/sim_1/behav/xsim/xsim.dir/sim_cpuclk_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 25 21:57:10 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e16e6402-c33f-4953-8936-9561aedc9333" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "74fea9643d264e8f8e4d8204cc7b9bbf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "7.41_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15448_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3937848750 -regid "" -xml F:/Github/Computer_Organization/src/project_14/project_14.sim/sim_1/behav/xsim/xsim.dir/sim_cpuclk_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Github/Computer_Organization/src/project_14/project_14.sim/sim_1/behav/xsim/xsim.dir/sim_cpuclk_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Github/Computer_Organization/src/project_14/project_14.sim/sim_1/behav/xsim/xsim.dir/sim_cpuclk_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
