# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/divux16_.xdc

# Block Designs: bd/divx16/divx16.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divx16 || ORIG_REF_NAME==divx16} -quiet] -quiet

# IP: bd/divx16/ip/divx16_clk_wiz_0/divx16_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divx16_clk_wiz_0 || ORIG_REF_NAME==divx16_clk_wiz_0} -quiet] -quiet

# IP: bd/divx16/ip/divx16_div_0_3/divx16_div_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divx16_div_0_3 || ORIG_REF_NAME==divx16_div_0_3} -quiet] -quiet

# XDC: bd/divx16/ip/divx16_clk_wiz_0/divx16_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==divx16_clk_wiz_0 || ORIG_REF_NAME==divx16_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/divx16/ip/divx16_clk_wiz_0/divx16_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==divx16_clk_wiz_0 || ORIG_REF_NAME==divx16_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/divx16/ip/divx16_clk_wiz_0/divx16_clk_wiz_0_ooc.xdc

# XDC: bd/divx16/ip/divx16_div_0_3/constrs_1/new/divux16_.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==divx16_div_0_3 || ORIG_REF_NAME==divx16_div_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/divx16/divx16_ooc.xdc
