# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/divux16/divux16.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divux16 || ORIG_REF_NAME==divux16} -quiet] -quiet

# IP: bd/divux16/ip/divux16_divu_0_1/divux16_divu_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divux16_divu_0_1 || ORIG_REF_NAME==divux16_divu_0_1} -quiet] -quiet

# IP: bd/divux16/ip/divux16_clk_wiz_0_1/divux16_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==divux16_clk_wiz_0_1 || ORIG_REF_NAME==divux16_clk_wiz_0_1} -quiet] -quiet

# XDC: bd/divux16/ip/divux16_clk_wiz_0_1/divux16_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==divux16_clk_wiz_0_1 || ORIG_REF_NAME==divux16_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/divux16/ip/divux16_clk_wiz_0_1/divux16_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==divux16_clk_wiz_0_1 || ORIG_REF_NAME==divux16_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/divux16/ip/divux16_clk_wiz_0_1/divux16_clk_wiz_0_1_ooc.xdc

# XDC: bd/divux16/divux16_ooc.xdc
