# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0.xci
# IP: The module: 'CPU_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0.xci
# IP: The module: 'CPU_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_clk_wiz_0_0/CPU_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
