# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mulx8.xdc

# Block Designs: bd/mulx8/mulx8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mulx8 || ORIG_REF_NAME==mulx8} -quiet] -quiet

# IP: bd/mulx8/ip/mulx8_mul_0_0/mulx8_mul_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mulx8_mul_0_0 || ORIG_REF_NAME==mulx8_mul_0_0} -quiet] -quiet

# XDC: bd/mulx8/mulx8_ooc.xdc
