# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_Ifetc32_0_0/CPU_Ifetc32_0_0.xci
# IP: The module: 'CPU_Ifetc32_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/ip/prgrom/prgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_Ifetc32_0_0/CPU_Ifetc32_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Ifetc32_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_Ifetc32_0_0/CPU_Ifetc32_0_0.xci
# IP: The module: 'CPU_Ifetc32_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/ip/prgrom/prgrom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc

# XDC: c:/Users/admin/Desktop/Computer Science/Digital Design/CPU/CPU.srcs/sources_1/bd/CPU/ip/CPU_Ifetc32_0_0/CPU_Ifetc32_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_Ifetc32_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
